### ISSUE TITLE
Neovim does not reload modified changes automatically (autoread)

### ISSUE THREAD

**Issue by salcode** [salcode/ironcode-vim#91]
I like the Vim `autoread` setting

> 	When a file has been detected to have been changed outside of Vim and
	it has not been changed inside of Vim, automatically read it again.
	When the file has been deleted this is not done.  |timestamp|
	If this option has a local value, use this command to switch back to
	using the global value:

but it doesn't work in Neovim at this time.

Adding this line

```
autocmd FocusGained * silent! checktime
```

fixes this behavior in neovim.

**Comment by salcode** [comment]
This has stopped working.

**Comment by salcode** [comment]
Updates load properly when not in tmux however when inside tmux 

```
:e!
```

is necessary to update the file.

**Comment by salcode** [comment]
The issue was with a tmux setting and has been resolved in my tmux settings, see https://github.com/salcode/ironcode-tmux/issues/24

**Comment by dagolinuxoid** [comment]
This is the only solution that did the job for me. Put it in your ~/.config/nvim/init.vim file
```
if ! exists("g:CheckUpdateStarted")
    let g:CheckUpdateStarted=1
    call timer_start(1,'CheckUpdate')
endif
function! CheckUpdate(timer)
    silent! checktime
    call timer_start(1000,'CheckUpdate')
endfunction
```

**Comment by salcode** [comment]
Thanks @dagolinuxoid 

I've resolved this problem on my system but it is interesting to hear how you solved it. I've outlined both our solutions below to make it easy for me to refer back to this issue.

## My Solution

I just confirmed that this issue was resolved for me by modifying my tmux configuration (see Iron Code tmux [Issue 24](https://github.com/salcode/ironcode-tmux/issues/24) *Neovim inside tmux does not update modified files*)

The key was adding

```
# Set focus-events on (important for Neovim autoread)
set -g focus-events on
```

to my tmux configuration

## Your Solution

If I'm reading this correctly, you've created a function (`CheckUpdate`) which:

- executes `checktime`
- waits 1 second (1000 milliseconds) and then calls itself to repeat the process

This seems like a reasonable solution.

**Comment by tankorsmash** [comment]
I don't use ironcode-vim, but this issue was at the top results for my neovim not autoreading my WSL changes when editing text in windows 10. The solution was to add

    autocmd FocusGained * checktime

to my `init.vim`. Hope this helps any wayward people!

**Comment by 9mm** [comment]
So this isn't working and I don't use tmux. Surely this is just something that can be done without adding autocommands?
